In [1]:
import pandas as pd
from io import StringIO

# Define the string
info_str = "<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 93 entries, 0 to 92\nData columns (total 8 columns):\n #   Column              Non-Null Count  Dtype  \n---  ------              --------------  -----  \n 0   Vegetable           93 non-null     object \n 1   Form                93 non-null     object \n 2   RetailPrice         93 non-null     float64\n 3   RetailPriceUnit     93 non-null     object \n 4   Yield               93 non-null     float64\n 5   CupEquivalentSize   93 non-null     float64\n 6   CupEquivalentUnit   93 non-null     object \n 7   CupEquivalentPrice  93 non-null     float64\ndtypes: float64(4), object(4)\nmemory usage: 5.9+ KB"

# Preprocess the string to remove unnecessary lines
info_lines = info_str.split('\n')[3:-3]
info_output = '\n'.join(info_lines)

# Use StringIO to create a file-like object for pandas to read from
info_file = StringIO(info_output)

# Read the file-like object using pd.read_csv() with appropriate parameters
info_df = pd.read_csv(info_file, sep='\s\s+', engine='python')

# Display the DataFrame
print(info_df)

     #             Column  Non-Null Count    Dtype
0  ---             ------  --------------    -----
1    0          Vegetable     93 non-null   object
2    1               Form     93 non-null   object
3    2        RetailPrice     93 non-null  float64
4    3    RetailPriceUnit     93 non-null   object
5    4              Yield     93 non-null  float64
6    5  CupEquivalentSize     93 non-null  float64
7    6  CupEquivalentUnit     93 non-null   object

In [2]:
info_df

     #             Column  Non-Null Count    Dtype
0  ---             ------  --------------    -----
1    0          Vegetable     93 non-null   object
2    1               Form     93 non-null   object
3    2        RetailPrice     93 non-null  float64
4    3    RetailPriceUnit     93 non-null   object
5    4              Yield     93 non-null  float64
6    5  CupEquivalentSize     93 non-null  float64
7    6  CupEquivalentUnit     93 non-null   object

In [3]:
import streamlit as st
import pandas as pd

class DataAnalyzer:
    def __init__(self, df):
        self.df = df

    def run(self):
        st.title('Data Analysis Options')
        choice = st.radio('Select Analysis Type', ['Data Info', 'Data Cleaning'])  # Add more options as needed

        if choice == 'Data Info':
            self.data_info()
        elif choice == 'Data Cleaning':
            self.data_cleaning()

    def data_info(self):
        st.subheader('DataFrame Info')
        info_output = self.get_info_output()
        st.text_area("DataFrame Info:", value=info_output, height=300)

        st.subheader('Categorical Columns')
        categorical_cols = self.get_categorical_columns()
        st.write(categorical_cols)

        st.subheader('Numerical Columns')
        numerical_cols = self.get_numerical_columns()
        st.write(numerical_cols)

    def get_info_output(self):
        import io
        import sys
        stdout = sys.stdout
        sys.stdout = io.StringIO()

        self.df.info()

        info_output = sys.stdout.getvalue()

        sys.stdout = stdout

        return info_output

    def get_categorical_columns(self):
        categorical_cols = self.df.select_dtypes(include=['object']).columns.tolist()
        return categorical_cols

    def get_numerical_columns(self):
        numerical_cols = self.df.select_dtypes(include=['number']).columns.tolist()
        return numerical_cols

    def data_cleaning(self):
        st.subheader('Data Cleaning Section')
        # Add data cleaning operations here

# Sample DataFrame
data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [30, 25, 35],
    'Gender': ['Male', 'Female', 'Male']
}
df = pd.DataFrame(data)

if __name__ == '__main__':
    app = DataAnalyzer(df)
    app.run()

2024-02-10 14:50:35.230
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/wambua/mike/Python/Streamlit_server/front_end/streamlit/lib/python3.10/site-packages/ipykernel_launcher.py [ARGUMENTS]